behaviors:
  MazeAgent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 3.0e-4 
      batch_size: 512
      buffer_size: 100000
      init_entcoef: 0.01
      tau: 0.005
      steps_per_update: 20
      save_replay_buffer: true
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 10000